# Generated by Django 6.0.5 on 2026-07-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_addgigdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/profile_pictures/'),
        ),
    ]
