# Generated by Django 6.0.5 on 2026-07-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bandprofile_profile_picture_sendmessagetoband'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessagetoband',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
