# Generated by Django 6.0.5 on 2026-07-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sendmessagetoband_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandprofile',
            name='song1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bandprofile',
            name='song2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
