# Generated by Django 6.0.5 on 2026-07-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bandprofile_song1_bandprofile_song2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandprofile',
            name='song1',
            field=models.FileField(blank=True, null=True, upload_to='bend_songs/'),
        ),
        migrations.AlterField(
            model_name='bandprofile',
            name='song2',
            field=models.FileField(blank=True, null=True, upload_to='bend_songs/'),
        ),
    ]
